name: sandbox_test_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  # network
  retrofit: 4.0.3
  dio: 5.3.4
  pretty_dio_logger: 1.3.1
  connectivity_plus: 5.0.2
  internet_connection_checker: 1.0.0+1

  #state
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  either_dart: 1.0.0
  flutter_dotenv: 5.1.0

  # forms
  mask_text_input_formatter: 2.6.0

  # ui
  gap: 3.0.1
  fluttertoast: 8.2.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  #runner
  build_runner: 2.4.4
  flutter_gen_runner: 5.3.1
  retrofit_generator: '>=7.0.0 <8.0.0'

  #generator
  freezed: 2.4.5
  json_serializable: 6.7.1


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
