name: sandbox_test_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  # network
  dio: ^5.3.4
  pretty_dio_logger: 1.3.1
  connectivity_plus: 5.0.2

  # forms
  mask_text_input_formatter: 2.6.0

  # ui
  gap: 3.0.1
  fluttertoast: 8.2.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
